title: "Marcus | Security Professional"
description: "Cybersecurity expertise, achievements, and portfolio."
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "dark"
url: "https://techByMarcus.github.io/aboutMarcus"
baseurl: ""
plugins:
  - jekyll-include-cache

# Author settings
author:
  name: "Marcus"
  avatar: "https://avatars.githubusercontent.com/u/00000000?v=4"
  bio: "Driven by a passion for cybersecurity, I deliver results through vision, collaboration, and relentless commitment to excellence."
  location: "Global"
  email: "marcus.security@email.com"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/your-linkedin"
      icon: "fab fa-linkedin"
